### ISSUE TITLE
Using library with Cognito Authorizer does not work

### ISSUE THREAD

**Issue by hassankhan** [jeremydaly/lambda-api#105]
Hi there @jeremydaly,

I've been having quite a bit of trouble with `lambda-api` trying to do the following with the Serverless Framework:

```yaml
handler: src/services/RestApi/Handler.default
timeout: 30
events:
  - http:
      method: any
      path: 'v1/{proxy+}'
      authorizer:
        arn: <USER_POOL_ARN>
```

If I disable the authorizer, everything works fine. Is this a known issue, or am I missing something obvious? 😕
