### ISSUE TITLE
Header not added inside error handling middleware

### ISSUE THREAD

**Issue by rodrigoreis22** [jeremydaly/lambda-api#109]
lambda-api version: 0.10.1

I have a middleware function to handle errors:

```
function errorHandler(err, req, res, next) {
  res.header('Access-Control-Allow-Origin', '*');
  console.error(err);
  if (err && err.message && err.message.toUpperCase() === 'UNAUTHORIZED') {
    return res.error(401, 'Unauthorized');
  }
  next();
}
```

I want this CORS headers to be added on every response, including the error ones.
In fact I already have another middleware that was supposed to be doing this, but it doesn't work:

```
function addCorsHeaders(req, res, next) {
  res.header('Access-Control-Allow-Origin', '*');
  next();
}
```

My api routing file:

```
const api = require('lambda-api')({ base: 'v2' })
  , middleware = require('../utils/middleware')
  , OEmbedApi = require('../apis/oEmbedApi');

api.use(middleware.addCorsHeaders);
api.use(middleware.populateCommonHeaders);
api.use(middleware.logRequest);
api.use(middleware.errorHandler);

api.get('/oembed/videoproxy', async (req, res) => {
  let videoUrl = await OEmbedApi.videoProxy(req.query.url);
  return res.redirect(307, videoUrl);
});

api.get('/oembed/imageproxy', async (req, res) => {
  let imageUrl = await OEmbedApi.imageProxy(req.query.url);
  return res.redirect(307, imageUrl);
});

api.post('/oembed/fetch', async (req, res) => {
  let response = await OEmbedApi.oEmbed(req.body.url, req.body.nativeCard);
  return res.json(response);
});

module.exports = api;
```

When the request fails with `401 - Unauthorized` the header `Access-Control-Allow-Origin` is not added.

This is my configuration on serverless.yml for this api:
```
oembed:
    handler: handler_oembed.oembed
    timeout: 20
    memorySize: 2536
    events:
      - http:
          path: oembed/{proxy+}
          method: ANY
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Preferred-Language
          cacheControl: 'max-age=3600, s-maxage=3600, proxy-revalidate'
```
